name: flutter_gif
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/saytoonz/flutter_gif

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
   